language: python
python:
  - "2.7"

sudo: false
cache:
  directories:
    - "~/.platformio"

install:
  - pip install -U platformio
  - platformio update

script:
  - platformio run -e ethernet-relay-temp-v1-debug -e ethernet-relay-temp-v1-debug-new -e ethernet-relay-temp-v1 -e ethernet-relay-temp-v1-new

notifications:
  email:
    on_success: change
    on_failure: change
